name: $name
version: $version
main: net.remodded.repaperutils.RePaperUtils
description: $description
load: STARTUP
authors:
  - ReModded
api-version: "$apiVersion"
loadbefore:
  - "Lands"
  - "PvPManager"
softdepend: 
  - "Lands"
  - "PvPManager"